cloud:
  aws:
    credentials:
      accessKey: ${{ secrets.AWS_ACCESS_KEY }}
      secretKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    s3:
      bucket: ${{ secrets.AWS_S3_BUCKET_NAME }}
    region:
      static: ap-northeast-2
    stack:
      auto: false
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  refresh: main 026 refresh
  access: main 026 jwt
server:
  port: 9090