name: Deploy-Server on AWS [dev]

on:
  push:
    branches: [ "dev" ]

permissions:
  contents: read

env:
  PROJECT_NAME: seb39_main_026_deploy

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Executing remote SSH Commands using SSH Key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER_NAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: sh /home/${{ secrets.SERVER_USER_NAME }}/$PROJECT_NAME/deploy.sh