name: Deploy Test with Gradle on Aws

on:
  push:
    branches: [ "deploy" ]

permissions:
  contents: read
  
env:
  S3_BUCKET_NAME: main026-s3

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Server Build 
      run: |                          # 개별 실행 옵션, 없으면 28 ~ 33줄까지 모두 한줄에 실행됨
        mkdir -p app/server/          # 압축할 임시 폴더 생성 (app/server)
        cd server/                    # 리포지토리에서 server 폴더로 이동
        chmod +x ./gradlew            # GitHub Action 에서 gradle build를 위한 권한설정
        ./gradlew clean bootjar -x test # 테스트를 제외한 빌드 진행, 테스트를 원하면 -x test 옵션 삭제
        cd ..                         # 리포지토리 기본 위치로 이동
        cp server/build/libs/*.jar app/server/  # jar 파일 임시 폴더로 복사
      shell: bash
  
    - name: Make zip file
      run: 
         zip -r deploy-server.zip ./app      # 임시 폴더 전체 deploy.zip 폴더로 
      shell: bash

    # Access Key와 Secret Access Key를 통해 권한을 확인합니다.
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    
    # 압축한 프로젝트를 S3로 전송합니다.
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./deploy-server.zip s3://$S3_BUCKET_NAME/deploy-server.zip
